name: Build macOS App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 1. Baixa o seu código
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configura o Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 3. Instala as dependências (DENTRO DA PASTA PCA)
    - name: Install dependencies
      working-directory: ./PCA # <-- MUDANÇA AQUI
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Cria o aplicativo (DENTRO DA PASTA PCA)
    - name: Build macOS Application
      working-directory: ./PCA # <-- MUDANÇA AQUI
      run: |
        pyinstaller --noconfirm --windowed --onefile --name "ConsultaPCA" main.py

    # 5. Salva o aplicativo para download
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ConsultaPCA-macOS
        path: PCA/dist/ConsultaPCA.app # <-- MUDANÇA AQUI
